import React, { useState } from 'react';
import { Shield, AlertTriangle, CheckCircle, XCircle, Activity, FileText, Download, Loader } from 'lucide-react';

const SecurityScanner = () => {
  const [targetUrl, setTargetUrl] = useState('');
  const [scanType, setScanType] = useState('quick');
  const [isScanning, setIsScanning] = useState(false);
  const [scanResults, setScanResults] = useState(null);
  const [scanHistory, setScanHistory] = useState([]);

  const performScan = async () => {
    if (!targetUrl) {
      alert('Please enter a target URL');
      return;
    }

    setIsScanning(true);
    
    // Simulate scanning process
    setTimeout(() => {
      const mockResults = {
        url: targetUrl,
        scanType: scanType,
        timestamp: new Date().toLocaleString(),
        totalVulnerabilities: Math.floor(Math.random() * 20) + 5,
        high: Math.floor(Math.random() * 5),
        medium: Math.floor(Math.random() * 8) + 2,
        low: Math.floor(Math.random() * 10) + 3,
        vulnerabilities: [
          {
            id: 1,
            name: 'SQL Injection',
            severity: 'High',
            description: 'Potential SQL injection vulnerability detected in login form',
            url: `${targetUrl}/login.php`,
            recommendation: 'Use parameterized queries and input validation'
          },
          {
            id: 2,
            name: 'Cross-Site Scripting (XSS)',
            severity: 'High',
            description: 'Reflected XSS found in search parameter',
            url: `${targetUrl}/search`,
            recommendation: 'Implement proper input sanitization and output encoding'
          },
          {
            id: 3,
            name: 'Missing Security Headers',
            severity: 'Medium',
            description: 'X-Frame-Options header not set',
            url: targetUrl,
            recommendation: 'Add X-Frame-Options: DENY header'
          },
          {
            id: 4,
            name: 'Weak Password Policy',
            severity: 'Medium',
            description: 'Password requirements are too lenient',
            url: `${targetUrl}/register`,
            recommendation: 'Enforce strong password requirements (min 8 chars, special characters)'
          },
          {
            id: 5,
            name: 'Information Disclosure',
            severity: 'Low',
            description: 'Server version exposed in HTTP headers',
            url: targetUrl,
            recommendation: 'Remove server version from response headers'
          }
        ]
      };

      setScanResults(mockResults);
      setScanHistory([mockResults, ...scanHistory]);
      setIsScanning(false);
    }, 3000);
  };

  const getSeverityColor = (severity) => {
    switch(severity.toLowerCase()) {
      case 'high': return 'text-red-600 bg-red-100';
      case 'medium': return 'text-yellow-600 bg-yellow-100';
      case 'low': return 'text-blue-600 bg-blue-100';
      default: return 'text-gray-600 bg-gray-100';
    }
  };

  const downloadReport = () => {
    if (!scanResults) return;
    
    const report = `
WEB APPLICATION SECURITY SCAN REPORT
====================================

Target URL: ${scanResults.url}
Scan Type: ${scanResults.scanType}
Date: ${scanResults.timestamp}

SUMMARY
-------
Total Vulnerabilities: ${scanResults.totalVulnerabilities}
High Risk: ${scanResults.high}
Medium Risk: ${scanResults.medium}
Low Risk: ${scanResults.low}

DETAILED FINDINGS
-----------------
${scanResults.vulnerabilities.map((v, i) => `
${i + 1}. ${v.name} [${v.severity}]
   Location: ${v.url}
   Description: ${v.description}
   Recommendation: ${v.recommendation}
`).join('\n')}

Generated by Web Security Scanner
    `;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `security_report_${Date.now()}.txt`;
    a.click();
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 p-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="flex items-center justify-center gap-3 mb-4">
            <Shield className="w-12 h-12 text-purple-400" />
            <h1 className="text-4xl font-bold text-white">Web Security Scanner</h1>
          </div>
          <p className="text-gray-300">Automated Vulnerability Detection & Reporting System</p>
        </div>

        {/* Scan Input Section */}
        <div className="bg-white/10 backdrop-blur-md rounded-xl p-6 mb-6 border border-white/20">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-2">
            <Activity className="w-5 h-5" />
            Start New Scan
          </h2>
          
          <div className="space-y-4">
            <div>
              <label className="block text-gray-300 mb-2">Target URL</label>
              <input
                type="text"
                value={targetUrl}
                onChange={(e) => setTargetUrl(e.target.value)}
                placeholder="https://example.com"
                className="w-full px-4 py-3 bg-white/5 border border-white/20 rounded-lg text-white placeholder-gray-400 focus:outline-none focus:border-purple-400"
              />
            </div>

            <div>
              <label className="block text-gray-300 mb-2">Scan Type</label>
              <select
                value={scanType}
                onChange={(e) => setScanType(e.target.value)}
                className="w-full px-4 py-3 bg-white/5 border border-white/20 rounded-lg text-white focus:outline-none focus:border-purple-400"
              >
                <option value="quick">Quick Scan (5-10 min)</option>
                <option value="standard">Standard Scan (15-30 min)</option>
                <option value="deep">Deep Scan (1-2 hours)</option>
              </select>
            </div>

            <button
              onClick={performScan}
              disabled={isScanning}
              className="w-full bg-purple-600 hover:bg-purple-700 disabled:bg-gray-600 text-white py-3 rounded-lg font-semibold flex items-center justify-center gap-2 transition-colors"
            >
              {isScanning ? (
                <>
                  <Loader className="w-5 h-5 animate-spin" />
                  Scanning in Progress...
                </>
              ) : (
                <>
                  <Shield className="w-5 h-5" />
                  Start Scan
                </>
              )}
            </button>
          </div>
        </div>

        {/* Scanning Progress */}
        {isScanning && (
          <div className="bg-white/10 backdrop-blur-md rounded-xl p-6 mb-6 border border-white/20">
            <div className="flex items-center gap-3 mb-4">
              <Loader className="w-6 h-6 text-purple-400 animate-spin" />
              <h3 className="text-lg font-semibold text-white">Scanning {targetUrl}...</h3>
            </div>
            <div className="space-y-2 text-gray-300">
              <p>✓ Spider crawling pages...</p>
              <p>✓ Passive vulnerability detection...</p>
              <p>⟳ Active security testing...</p>
            </div>
          </div>
        )}

        {/* Results Section */}
        {scanResults && !isScanning && (
          <>
            {/* Summary Cards */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
              <div className="bg-white/10 backdrop-blur-md rounded-xl p-6 border border-white/20">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-gray-400 text-sm">Total Issues</p>
                    <p className="text-3xl font-bold text-white">{scanResults.totalVulnerabilities}</p>
                  </div>
                  <AlertTriangle className="w-10 h-10 text-purple-400" />
                </div>
              </div>

              <div className="bg-red-500/20 backdrop-blur-md rounded-xl p-6 border border-red-500/30">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-red-200 text-sm">High Risk</p>
                    <p className="text-3xl font-bold text-red-400">{scanResults.high}</p>
                  </div>
                  <XCircle className="w-10 h-10 text-red-400" />
                </div>
              </div>

              <div className="bg-yellow-500/20 backdrop-blur-md rounded-xl p-6 border border-yellow-500/30">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-yellow-200 text-sm">Medium Risk</p>
                    <p className="text-3xl font-bold text-yellow-400">{scanResults.medium}</p>
                  </div>
                  <AlertTriangle className="w-10 h-10 text-yellow-400" />
                </div>
              </div>

              <div className="bg-blue-500/20 backdrop-blur-md rounded-xl p-6 border border-blue-500/30">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-blue-200 text-sm">Low Risk</p>
                    <p className="text-3xl font-bold text-blue-400">{scanResults.low}</p>
                  </div>
                  <CheckCircle className="w-10 h-10 text-blue-400" />
                </div>
              </div>
            </div>

            {/* Vulnerabilities List */}
            <div className="bg-white/10 backdrop-blur-md rounded-xl p-6 mb-6 border border-white/20">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-semibold text-white flex items-center gap-2">
                  <FileText className="w-5 h-5" />
                  Detailed Findings
                </h2>
                <button
                  onClick={downloadReport}
                  className="flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg transition-colors"
                >
                  <Download className="w-4 h-4" />
                  Download Report
                </button>
              </div>

              <div className="space-y-4">
                {scanResults.vulnerabilities.map((vuln) => (
                  <div key={vuln.id} className="bg-white/5 rounded-lg p-4 border border-white/10">
                    <div className="flex items-start justify-between mb-2">
                      <h3 className="text-lg font-semibold text-white">{vuln.name}</h3>
                      <span className={`px-3 py-1 rounded-full text-sm font-medium ${getSeverityColor(vuln.severity)}`}>
                        {vuln.severity}
                      </span>
                    </div>
                    <p className="text-gray-300 mb-2">{vuln.description}</p>
                    <p className="text-sm text-gray-400 mb-2">
                      <strong>Location:</strong> {vuln.url}
                    </p>
                    <div className="bg-green-900/30 border border-green-700/50 rounded p-3 mt-3">
                      <p className="text-sm text-green-300">
                        <strong>💡 Recommendation:</strong> {vuln.recommendation}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </>
        )}

        {/* Scan History */}
        {scanHistory.length > 0 && (
          <div className="bg-white/10 backdrop-blur-md rounded-xl p-6 border border-white/20">
            <h2 className="text-xl font-semibold text-white mb-4">Scan History</h2>
            <div className="space-y-2">
              {scanHistory.slice(0, 5).map((scan, idx) => (
                <div key={idx} className="bg-white/5 rounded-lg p-3 flex justify-between items-center">
                  <div>
                    <p className="text-white font-medium">{scan.url}</p>
                    <p className="text-gray-400 text-sm">{scan.timestamp}</p>
                  </div>
                  <div className="flex gap-4">
                    <span className="text-red-400">{scan.high} High</span>
                    <span className="text-yellow-400">{scan.medium} Med</span>
                    <span className="text-blue-400">{scan.low} Low</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default SecurityScanner;
